# @package _global_
checkpoint: null # add checkpoint path here
tensorboard: true
auto_cpu_if_no_gpu: true
device: cuda:0
save: true
global_seed: null
save_preds: false
run_averaged_on_train: false

dataset:
  train:
    use: true
  val:
    use: true
  test:
    use: true
