defaults:
  - dataset: cifar10
  - model: resnet20
  - hparams: default_he
  - optimizer: momentum
  - scheduler: multistep_he
  - averaged: ema
  - misc: train_misc
  - override hydra/job_logging: custom
  - override hydra/output: custom
