# From He et al., originally designed for ImageNet and adapted for CIFAR
_target_: src.network.resnet_imagenet.resnet18
num_classes: 10
# more info: https://hydra.cc/docs/patterns/specializing_config
